### ISSUE TITLE
moldoc images showing locally but not on ReadtheDocs

### ISSUE THREAD

**Issue by TimoSommer** [lukasturcani/moldoc#12]
Hey Lukas, 

it's me again :) We have progressed with our package and have published our documentation now to ReadtheDocs. However, in the online documentation, the moldoc images are not showing, it's just blank. Locally, they do show though. In addition, there is no error message in the build from ReadtheDocs, it just fails silently. 

You can see the issue in the [documentation](https://dartassembler.readthedocs.io/en/latest/doc_files/1_quickstart.html). If you scroll down a little, underneath the green info box that mentions moldoc, there should be three moldoc images of molecules. I have attached a screenshot of how it looks when I render the documentation locally. 

Do you have any experience in this issue? I find it very hard to debug because I don't know where it fails.

![Screenshot](https://github.com/user-attachments/assets/c800a301-5658-4ca0-8325-c17a2f3bd74f)

**Comment by lukasturcani** [comment]
Hi Timo! Thanks again for using the library, giving it a shout-out in your docs and reporting your issues!

So. I normally use the furo theme (https://github.com/pradyunsg/furo), it looks like this theme has a bug. It means that the scripts which moldoc needs to insert are inserted at the end of the HTML file. I thought this was just sphinx being weird and so i "fixed" it. this means everything runs fine if you use the furo theme. 

Not so good if you're using a different theme. 

I'll try to have a fix out today.

**Comment by lukasturcani** [comment]
I've reported an issue with `furo` https://github.com/pradyunsg/furo/discussions/850 but will try to come up with a patch that fixes this immediately

**Comment by lukasturcani** [comment]
I've released version 3.0.5 -- hopefully that should fix it! Let me know if that's not the case and I will re-open the issue

**Comment by TimoSommer** [comment]
Thank you, it works perfectly now, even with my current theme! This closes the following issue in the DARTassembler package: https://github.com/CCEMGroupTCD/DARTassembler/issues/2
